apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  s3-access-key: {{ .Values.s3.accessKey | quote }}
  s3-secret-key: {{ .Values.s3.secretKey | quote }}
  admin-password: {{ .Values.auth.adminPass | default (randAlphaNum 24) | quote }}
  jwt-secret: {{ .Values.auth.jwtSecret | default (randAlphaNum 64) | quote }}
  {{- if and .Values.ldap.enabled .Values.ldap.bindPassword }}
  ldap-bind-password: {{ .Values.ldap.bindPassword | quote }}
  {{- end }}
  {{- if .Values.oauth.google.clientSecret }}
  oauth-google-secret: {{ .Values.oauth.google.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oauth.github.clientSecret }}
  oauth-github-secret: {{ .Values.oauth.github.clientSecret | quote }}
  {{- end }}
